# Generated by Django 5.1.1 on 2024-10-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_amenities_hotel_hotelbooking_hotelimages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='User',
            new_name='user',
        ),
    ]
