# Generated by Django 5.1.1 on 2024-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_hotelbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.TextField(default='pune'),
            preserve_default=False,
        ),
    ]
