# Generated by Django 5.1.1 on 2024-12-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hotelbooking_phone_number_hotelbooking_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='adults_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='babies_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
