# Generated by Django 5.1.1 on 2024-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hotelbooking_adults_count_hotelbooking_babies_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
